### ISSUE TITLE
WARNING: Could not send HEAD request to   HTTP Error 403: Forbidden platzi

### ISSUE THREAD

**Issue by developcreativo** [haruhi-dl/haruhi-dl#14]
```
 haruhi-dl  "https://platzi.com/cursos/react-router/" --cookies ./cookies.txt -v --no-headless-playwright --force-playwright-browser=chromium
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://platzi.com/cursos/react-router/', '--cookies', './cookies.txt', '-v', '--no-headless-playwright', '--force-playwright-browser=chromium']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] haruhi-dl version 2021.08.01
[debug] Lazy loading extractors enabled
[debug] Git HEAD: fe26ced
[debug] Python version 3.9.9 (CPython) - Linux-5.15.45-amd64-desktop-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.4, ffprobe 4.3.4, playwright 1.24.1
[debug] Proxy map: {}
[generic] react-router: Requesting header
WARNING: Could not send HEAD request to https://platzi.com/cursos/react-router/: HTTP Error 403: Forbidden
[generic] react-router: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] react-router: Extracting information
ERROR: Unsupported URL: https://platzi.com/cursos/react-router/
Traceback (most recent call last):
  File "/home/development/Documents/Download-platzi/venv/lib/python3.9/site-packages/haruhi_dl/HaruhiDL.py", line 827, in wrapper
    return func(self, *args, **kwargs)
  File "/home/development/Documents/Download-platzi/venv/lib/python3.9/site-packages/haruhi_dl/HaruhiDL.py", line 848, in __extract_info
    ie_result = ie.extract(url)
  File "/home/development/Documents/Download-platzi/venv/lib/python3.9/site-packages/haruhi_dl/extractor/common.py", line 549, in extract
    ie_result = self._real_extract(url)
  File "/home/development/Documents/Download-platzi/venv/lib/python3.9/site-packages/haruhi_dl/extractor/generic.py", line 3397, in _real_extract
    raise UnsupportedError(url)
haruhi_dl.utils.UnsupportedError: Unsupported URL: https://platzi.com/cursos/react-router/
```

**Comment by selfisekai** [comment]
haruhi-dl is no longer maintained, use [yt-dlp](https://github.com/yt-dlp/yt-dlp) instead
